[language-server.elixir-ls]
command = "/home/borpht/elixir-ls/_build/language_server.sh"

[[language]]
name = "elixir"
language-servers = ["elixir-ls"]

[[language]]
name = "heex"
language-servers = ["elixir-ls"]

[language-server.tailwind-heex]

command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "elixir"
language-id = "phoenix-heex"
language-servers = ["tailwind-heex", "elixir-ls"]
auto-format = true

[[language]]
name = "heex"
language-id = "phoenix-heex"
language-servers = ["tailwind-heex", "elixir-ls"]
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "babel"] }
auto-format = true

